version: '3'
services:
    api:
        build:
            context: ./nodejs-healthcheck-backend
        container_name: api_node_service
        env_file: .env
        ports:
            - "4090:4090"
        depends_on:
            - "prisma"
    cron:
        build:
            context: ./nodejs-healthcheck-cron-scripts
        container_name: api_cron_service
        env_file: .env
        ports:
            - "4130:4130"
        depends_on:
            - "prisma"            
    prisma:
        image: prismagraphql/prisma:1.34
        ports:
            - '4466:4466'
        depends_on:
            - "postgres"            
        environment:
            PRISMA_CONFIG: |
                port: 4466
                databases:
                    default:
                        connector: postgres
                        host: postgres
                        port: 5432
                        user: prisma
                        password: prisma
    postgres:
        image: postgres:10.3
        environment:
            POSTGRES_USER: prisma
            POSTGRES_PASSWORD: prisma
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    postgres: ~
